### ISSUE TITLE
Rspec/LetSetup

### ISSUE THREAD

**Issue by rhunterharris** [sendoso/rubocop-sendoso#12]
See discussion here https://github.com/datarockets/ruby-style/issues/58 about LetSetup.  LetSetup prevents us from using let! to set up data in the DB, instead prefering before blocks.  let! is a wrapper around before, so I suggest setting this cop to explicitly be false.

**Comment by marcferna** [comment]
I think it already complains if we use `let!` without an explicit reference within the test no?

**Comment by rhunterharris** [comment]
Correct - this would remove that complaint and allow you to do let! to set up data instead of (potentially multiple) before blocks.  This is a suggestion to disable LetSetup, that may not have been explicit/clear

**Comment by rhunterharris** [comment]
Mislinked - reopened
