### ISSUE TITLE
Rails/SkipsModelValidations is purposefully used in data migrations

### ISSUE THREAD

**Issue by rhunterharris** [sendoso/rubocop-sendoso#13]
We're frequently disabling Rails/SkipsModelValidations when we're doing data migrations.  I suggest whitelisting this for data migrations.  We're also allowing this in specs in the monolith, so I suggest whitelisting these as well.

**Comment by marcferna** [comment]
Agree

**Comment by rhunterharris** [comment]
PR here https://github.com/sendoso/rubocop-sendoso/pull/15
